(test
 (name test_core)
 (modules test_core)
 (libraries asko unix))

(test
 (name test_store)
 (modules test_store)
 (libraries asko unix yojson))

(test
 (name test_http)
 (modules test_http)
 (libraries asko unix yojson lwt.unix))

(test
 (name test_summary)
 (modules test_summary)
 (libraries asko unix yojson))

(test
 (name test_pipeline)
 (modules test_pipeline)
 (libraries asko unix yojson sqlite3 lwt.unix cohttp-lwt-unix))

(test
 (name test_web_fetch)
 (modules test_web_fetch)
 (libraries asko lwt.unix cohttp-lwt-unix ipaddr))
